# Generated by Django 2.1.2 on 2018-12-17 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myUsers', '0005_auto_20181120_2321'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserLoginInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uId', models.CharField(max_length=10, verbose_name='用户编号')),
                ('uLoginTime', models.DateTimeField(verbose_name='用户上次登录时间')),
                ('uLoginIP', models.CharField(max_length=15, verbose_name='用户登录IP地址')),
            ],
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='uLastLoginTime',
        ),
    ]
