# Generated by Django 2.1.2 on 2018-12-17 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myUsers', '0006_auto_20181217_1544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userlogininfo',
            name='uLoginTime',
            field=models.DateTimeField(verbose_name='用户登录时间'),
        ),
    ]
