# Generated by Django 2.1.2 on 2018-12-17 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myUsers', '0007_auto_20181217_1556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userlogininfo',
            name='uLoginTime',
            field=models.DateTimeField(auto_now_add=True, verbose_name='用户登录时间'),
        ),
    ]
