# Generated by Django 2.1.2 on 2018-12-24 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myUsers', '0008_auto_20181217_1604'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegisterKeyInfo',
            fields=[
                ('rId', models.CharField(max_length=32, primary_key=True, serialize=False, verbose_name='注册邀请码编号')),
            ],
        ),
        migrations.AddField(
            model_name='userinfo',
            name='uEnabled',
            field=models.BooleanField(default=True, verbose_name='用户账户启用标识'),
        ),
    ]
