# Generated by Django 2.1.2 on 2018-11-20 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EssayInfo',
            fields=[
                ('eId', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='文章编号')),
                ('eTitle', models.CharField(max_length=64, verbose_name='文章标题')),
                ('eText', models.TextField(verbose_name='文章主体')),
                ('eIsPublic', models.BooleanField(verbose_name='文章是否公开')),
                ('eUploadTime', models.DateTimeField(verbose_name='文章上传时间')),
                ('eUserId', models.CharField(max_length=10, verbose_name='文章所属用户编号')),
            ],
        ),
    ]
