# Generated by Django 2.1.2 on 2018-11-20 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myCloud', '0002_fileinfo_ffile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileinfo',
            name='fFile',
            field=models.FileField(blank=True, null=True, upload_to='%Y%m%d%H%M', verbose_name='文件（路径）'),
        ),
    ]
