# Generated by Django 2.1.2 on 2018-11-20 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myCloud', '0003_auto_20181120_0901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileinfo',
            name='fFile',
            field=models.FileField(blank=True, null=True, upload_to='\\%Y%m%d%H%M\\', verbose_name='文件（路径）'),
        ),
    ]
