# Generated by Django 2.1.2 on 2018-12-17 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myCloud', '0004_auto_20181120_0904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileinfo',
            name='fUploadTime',
            field=models.DateTimeField(auto_now_add=True, verbose_name='文件上传时间'),
        ),
    ]
