# Generated by Django 2.1.2 on 2018-12-24 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myCloud', '0005_auto_20181217_1544'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fileinfo',
            old_name='fFloderId',
            new_name='fFolderId',
        ),
        migrations.RenameField(
            model_name='fileinfo',
            old_name='fIsFloder',
            new_name='fIsFolder',
        ),
    ]
