# Generated by Django 2.1.2 on 2018-12-24 22:56

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myCloud', '0008_auto_20181224_2248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileinfo',
            name='fFile',
            field=models.FileField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(location='upload/'), upload_to='cloud_files/', verbose_name='文件（路径）'),
        ),
    ]
