# Generated by Django 2.1.2 on 2019-01-17 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myCloud', '0011_auto_20190116_2352'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileTypeInfo',
            fields=[
                ('fExtension', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='文件后缀')),
                ('fType', models.CharField(max_length=16, verbose_name='文件类型')),
            ],
        ),
    ]
